apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-demo
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: devops-demo
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
